theme: jekyll-theme-hacker
title: [Scheme+ programing language by Damien Mattei]
description: [Enhancing Scheme (and Lisp-like) languages.]
show_downloads: true


#Others
markdown: kramdown

# Syntax highlighting
highlighter: pygments
kramdown:
    input: GFM 
    syntax_highlighter: pygments
    
    